build: codecheck test
	rm -fr ./vendor
	CGO_ENABLED=0  go build -ldflags="-s -w" -o bin/sachista-chess-perft perft/main.go

codecheck:
	go fmt ./...
	go fix ./...
	go vet ./...
	go run honnef.co/go/tools/cmd/staticcheck ./...

test:
	go test ./...

